
var proverbs = [];

proverbs.push("A cat may look at a king");
proverbs.push("A chain is only as strong as its weakest link");
proverbs.push("A change is as good as a rest");
proverbs.push("A dog is a man's best friend");
proverbs.push("A drowning man will clutch at a straw");
proverbs.push("A fish always rots from the head down");
proverbs.push("A fool and his money are soon parted");
proverbs.push("A friend in need is a friend indeed");
proverbs.push("A golden key can open any door");
proverbs.push("A good beginning makes a good ending");
proverbs.push("A good man is hard to find");
proverbs.push("A house divided against itself cannot stand");
proverbs.push("A house is not a home");
proverbs.push("A journey of a thousand miles begins with a single step");
proverbs.push("A leopard cannot change its spots");
proverbs.push("A little knowledge is a dangerous thing");
proverbs.push("A little learning is a dangerous thing");
proverbs.push("A little of what you fancy does you good");
proverbs.push("A man who is his own lawyer has a fool for his client");
proverbs.push("A miss is as good as a mile");
proverbs.push("A new broom sweeps clean");
proverbs.push("A nod's as good as a wink to a blind horse");
proverbs.push("A penny saved is a penny earned");
proverbs.push("A person is known by the company he keeps");
proverbs.push("A picture paints a thousand words");
proverbs.push("A place for everything and everything in its place");
proverbs.push("A poor workman always blames his tools");
proverbs.push("A problem shared is a problem halved");
proverbs.push("A prophet is not recognized in his own land");
proverbs.push("A rising tide lifts all boats");
proverbs.push("A rolling stone gathers no moss");
proverbs.push("A soft answer turneth away wrath");
proverbs.push("A stitch in time saves nine");
proverbs.push("A swarm in May is worth a load of hay; a swarm in June is worth a silver spoon; but a swarm in July is not worth a fly");
proverbs.push("A thing of beauty is a joy forever");
proverbs.push("A trouble shared is a trouble halved");
proverbs.push("A volunteer is worth twenty pressed men");
proverbs.push("A watched pot never boils");
proverbs.push("A woman's place is in the home");
proverbs.push("A woman's work is never done");
proverbs.push("A word to the wise is enough");
proverbs.push("Absence makes the heart grow fonder");
proverbs.push("Absolute power corrupts absolutely");
proverbs.push("Accidents will happen (in the best-regulated families).");
proverbs.push("Actions speak louder than words");
proverbs.push("Adversity makes strange bedfellows");
proverbs.push("After a storm comes a calm");
proverbs.push("All good things come to he who waits");
proverbs.push("All good things must come to an end");
proverbs.push("All is grist that comes to the mill");
proverbs.push("All publicity is good publicity");
proverbs.push("All roads lead to Rome");
proverbs.push("All that glisters is not gold");
proverbs.push("All that glitters is not gold");
proverbs.push("All the world loves a lover");
proverbs.push("All things come to those who wait");
proverbs.push("All things must pass");
proverbs.push("All work and no play makes Jack a dull boy");
proverbs.push("All you need is love");
proverbs.push("All's fair in love and war");
proverbs.push("All's for the best in the best of all possible worlds");
proverbs.push("All's well that ends well");
proverbs.push("A miss is as good as a mile");
proverbs.push("An apple a day keeps the doctor away");
proverbs.push("An army marches on its stomach");
proverbs.push("An Englishman's home is his castle");
proverbs.push("An ounce of prevention is worth a pound of cure");
proverbs.push("Another day, another dollar");
proverbs.push("Any port in a storm");
proverbs.push("April showers bring forth May flowers");
proverbs.push("As thick as thieves");
proverbs.push("As you make your bed, so you must lie upon it");
proverbs.push("As you sow so shall you reap");
proverbs.push("Ask a silly question and you'll get a silly answer");
proverbs.push("Ask no questions and hear no lies");
proverbs.push("Attack is the best form of defence");
proverbs.push("Bad money drives out good");
proverbs.push("Bad news travels fast");
proverbs.push("Barking dogs seldom bite");
proverbs.push("Beauty is in the eye of the beholder");
proverbs.push("Beauty is only skin deep");
proverbs.push("Beggars should not be choosers");
proverbs.push("Behind every great man there's a great woman");
proverbs.push("Better late than never");
proverbs.push("Better safe than sorry");
proverbs.push("Better the Devil you know than the Devil you don't");
proverbs.push("Better to have loved and lost than never to have loved at all");
proverbs.push("Better to light a candle than to curse the darkness");
proverbs.push("Better to remain silent and be thought a fool that to speak and remove all doubt");
proverbs.push("Beware of Greeks bearing gifts");
proverbs.push("Beware the Ides of March");
proverbs.push("Big fish eat little fish");
proverbs.push("Birds of a feather flock together");
proverbs.push("Blood is thicker than water");
proverbs.push("Boys will be boys");
proverbs.push("Brevity is the soul of wit");
proverbs.push("Business before pleasure");
proverbs.push("Caesar's wife must be above suspicion");
proverbs.push("Carpe diem (Pluck the day; Seize the day)");
proverbs.push("Charity begins at home");
proverbs.push("Cheats never prosper");
proverbs.push("Children should be seen and not heard");
proverbs.push("Cleanliness is next to godliness");
proverbs.push("Clothes make the man");
proverbs.push("Cold hands, warm heart");
proverbs.push("Comparisons are odious");
proverbs.push("Count your blessings");
proverbs.push("Cowards may die many times before their death");
proverbs.push("Crime doesn't pay");
proverbs.push("Cut your coat to suit your cloth");
proverbs.push("Dead men tell no tales");
proverbs.push("Devil take the hindmost");
proverbs.push("Discretion is the better part of valour");
proverbs.push("Distance lends enchantment to the view");
proverbs.push("Do as I say, not as I do");
proverbs.push("Do as you would be done by");
proverbs.push("Do unto others as you would have them do to you");
proverbs.push("Don't bite the hand that feeds you");
proverbs.push("Don't burn your bridges behind you");
proverbs.push("Don't cast your pearls before swine");
proverbs.push("Don't change horses in midstream");
proverbs.push("Don't count your chickens before they are hatched");
proverbs.push("Don't cross the bridge till you come to it");
proverbs.push("Don't cut off your nose to spite your face");
proverbs.push("Don't keep a dog and bark yourself");
proverbs.push("Don't let the bastards grind you down");
proverbs.push("Don't look a gift horse in the mouth");
proverbs.push("Don't meet troubles half-way");
proverbs.push("Don't put all your eggs in one basket");
proverbs.push("Don't put the cart before the horse");
proverbs.push("Don't put new wine into old bottles");
proverbs.push("Don't rock the boat");
proverbs.push("Don't spoil the ship for a ha'porth of tar");
proverbs.push("Don't throw pearls to swine");
proverbs.push("Don't teach your Grandma to suck eggs");
proverbs.push("Don't throw the baby out with the bathwater");
proverbs.push("Don't try to walk before you can crawl");
proverbs.push("Don't upset the apple-cart");
proverbs.push("Don't wash your dirty linen in public");
proverbs.push("Doubt is the beginning not the end of wisdom");
proverbs.push("Early to bed and early to rise, makes a man healthy, wealthy and wise");
proverbs.push("East is east, and west is west");
proverbs.push("East, west, home's best");
proverbs.push("Easy come, easy go");
proverbs.push("Eat, drink and be merry, for tomorrow we die");
proverbs.push("Empty vessels make the most noise");
proverbs.push("Enough is as good as a feast");
proverbs.push("Enough is enough");
proverbs.push("Even a worm will turn");
proverbs.push("Every cloud has a silver lining");
proverbs.push("Every dog has its day");
proverbs.push("Every Jack has his Jill");
proverbs.push("Every little helps");
proverbs.push("Every man for himself, and the Devil take the hindmost");
proverbs.push("Every man has his price");
proverbs.push("Every picture tells a story");
proverbs.push("Every stick has two ends");
proverbs.push("Everyone wants to go to heaven but nobody wants to die");
proverbs.push("Everything comes to him who waits");
proverbs.push("Failing to plan is planning to fail");
proverbs.push("Faint heart never won fair lady");
proverbs.push("Fair exchange is no robbery");
proverbs.push("Faith will move mountains");
proverbs.push("Familiarity breeds contempt");
proverbs.push("Feed a cold and starve a fever");
proverbs.push("Fight fire with fire");
proverbs.push("Finders keepers, losers weepers");
proverbs.push("Fine words butter no parsnips");
proverbs.push("First come, first served");
proverbs.push("First impressions are the most lasting");
proverbs.push("First things first");
proverbs.push("Fish always stink from the head down");
proverbs.push("Fish and guests smell after three days");
proverbs.push("Flattery will get you nowhere");
proverbs.push("Fools rush in where angels fear to tread");
proverbs.push("For want of a nail the shoe was lost; for want of a shoe the horse was lost; and for want of a horse the man was lost");
proverbs.push("Forewarned is forearmed");
proverbs.push("Forgive and forget");
proverbs.push("Fortune favours the brave");
proverbs.push("From the sublime to the ridiculous is only one step");
proverbs.push("Genius is an infinite capacity for taking pains");
proverbs.push("Genius is one percent inspiration, ninety-nine percent perspiration");
proverbs.push("Give a dog a bad name and hang him");
proverbs.push("Give a man a fish and you will feed him for a day...");
proverbs.push("Give a man enough rope and he will hang himself");
proverbs.push("Give credit where credit is due");
proverbs.push("God helps those who help themselves");
proverbs.push("Good fences make good neighbours");
proverbs.push("Good talk saves the food");
proverbs.push("Good things come to those who wait");
proverbs.push("Great minds think alike");
proverbs.push("Half a loaf is better than no bread");
proverbs.push("Handsome is as handsome does");
proverbs.push("Hard cases make bad law");
proverbs.push("Hard work never did anyone any harm");
proverbs.push("Haste makes waste");
proverbs.push("He that goes a-borrowing, goes a-sorrowing");
proverbs.push("He who can does, he who cannot, teaches");
proverbs.push("He who fights and runs away, may live to fight another day");
proverbs.push("He who hesitates is lost");
proverbs.push("He who laughs last laughs longest");
proverbs.push("He who lives by the sword shall die by the sword");
proverbs.push("He who pays the piper calls the tune");
proverbs.push("He who sups with the Devil should have a long spoon");
proverbs.push("Hell hath no fury like a woman scorned");
proverbs.push("Hindsight is always twenty-twenty");
proverbs.push("History repeats itself");
proverbs.push("Home is where the heart is");
proverbs.push("Honesty is the best policy");
proverbs.push("Hope springs eternal");
proverbs.push("Horses for courses");
proverbs.push("If anything can go wrong, it will");
proverbs.push("If a job is worth doing it is worth doing well");
proverbs.push("If at first you don't succeed try, try and try again");
proverbs.push("If God had meant us to fly he'd have given us wings");
proverbs.push("If ifs and ands were pots and pans there'd be no work for tinkers");
proverbs.push("If it ain't broke, don't fix it");
proverbs.push("If life deals you lemons, make lemonade");
proverbs.push("If the cap fits, wear it");
proverbs.push("If the mountain won't come to Mohammed, then Mohammed must go to the mountain");
proverbs.push("If the shoe fits, wear it");
proverbs.push("If wishes were horses, beggars would ride");
proverbs.push("If you can't be good, be careful");
proverbs.push("If you can't beat em, join em");
proverbs.push("If you can't stand the heat get out of the kitchen");
proverbs.push("If you lie down with dogs, you will get up with fleas");
proverbs.push("If you pay peanuts, you get monkeys");
proverbs.push("If you want a thing done well, do it yourself");
proverbs.push("Ignorance is bliss");
proverbs.push("Imitation is the sincerest form of flattery");
proverbs.push("In for a penny, in for a pound");
proverbs.push("In the kingdom of the blind the one eyed man is king");
proverbs.push("In the midst of life we are in death");
proverbs.push("Into every life a little rain must fall");
proverbs.push("It ain't over till the fat lady sings");
proverbs.push("It goes without saying");
proverbs.push("It is best to be on the safe side");
proverbs.push("It is better to give than to receive");
proverbs.push("It is easy to be wise after the event");
proverbs.push("It never rains but it pours");
proverbs.push("It takes a thief to catch a thief");
proverbs.push("It takes all sorts to make a world");
proverbs.push("It takes one to know one");
proverbs.push("It takes two to tango");
proverbs.push("It's all grist to the mill");
proverbs.push("It's an ill wind that blows no one any good");
proverbs.push("It's better to give than to receive");
proverbs.push("It's better to have loved and lost than never to have loved at all");
proverbs.push("It's better to light a candle than curse the darkness");
proverbs.push("It's better to travel hopefully than to arrive");
proverbs.push("It's never too late");
proverbs.push("It's no use crying over spilt milk");
proverbs.push("It's no use locking the stable door after the horse has bolted");
proverbs.push("It's the early bird that catches the worm");
proverbs.push("It's the empty can that makes the most noise");
proverbs.push("It's the squeaky wheel that gets the grease");
proverbs.push("Jack of all trades, master of none");
proverbs.push("Judge not, that ye be not judged");
proverbs.push("Keep your chin up");
proverbs.push("Keep your powder dry");
proverbs.push("Laugh and the world laughs with you, weep and you weep alone");
proverbs.push("Laughter is the best medicine");
proverbs.push("Least said, soonest mended");
proverbs.push("Less is more");
proverbs.push("Let bygones be bygones");
proverbs.push("Let not the sun go down on your wrath");
proverbs.push("Let sleeping dogs lie");
proverbs.push("Let the buyer beware");
proverbs.push("Let the dead bury the dead");
proverbs.push("Let the punishment fit the crime");
proverbs.push("Let well alone");
proverbs.push("Life begins at forty");
proverbs.push("Life is just a bowl of cherries");
proverbs.push("Life is what you make it");
proverbs.push("Life's not all beer and skittles");
proverbs.push("Lightning never strikes twice in the same place");
proverbs.push("Like father, like son");
proverbs.push("Little pitchers have big ears");
proverbs.push("Little strokes fell great oaks");
proverbs.push("Little things please little minds");
proverbs.push("Live for today for tomorrow never comes");
proverbs.push("Look before you leap");
proverbs.push("Love is blind");
proverbs.push("Love makes the world go round");
proverbs.push("Love thy neighbour as thyself");
proverbs.push("Love will find a way");
proverbs.push("Make hay while the sun shines");
proverbs.push("Make love not war");
proverbs.push("Man does not live by bread alone");
proverbs.push("Manners maketh man");
proverbs.push("Many a little makes a mickle");
proverbs.push("Many a mickle makes a muckle");
proverbs.push("Many a true word is spoken in jest");
proverbs.push("Many hands make light work");
proverbs.push("March comes in like a lion, and goes out like a lamb");
proverbs.push("March winds and April showers bring forth May flowers");
proverbs.push("Marriages are made in heaven");
proverbs.push("Marry in haste, repent at leisure");
proverbs.push("Might is right");
proverbs.push("Mighty oaks from little acorns grow");
proverbs.push("Misery loves company");
proverbs.push("Moderation in all things");
proverbs.push("Monday's child is fair of face, ");
proverbs.push("Tuesday's child is full of grace,");
proverbs.push("Wednesday's child is full of woe,");
proverbs.push("Thursday's child has far to go,");
proverbs.push("Friday's child is loving and giving,");
proverbs.push("Saturday's child works hard for its living,");
proverbs.push("And a child that's born on the Sabbath day");
proverbs.push("Is fair and wise and good and gay.");
proverbs.push("Money doesn't grow on trees");
proverbs.push("Money is the root of all evil");
proverbs.push("Money isn't everything");
proverbs.push("Money makes the world go round");
proverbs.push("Money talks");
proverbs.push("More haste, less speed");
proverbs.push("Music has charms to soothe the savage breast");
proverbs.push("Nature abhors a vacuum");
proverbs.push("Necessity is the mother of invention");
proverbs.push("Needs must when the devil drives");
proverbs.push("Ne'er cast a clout till May be out");
proverbs.push("Never give a sucker an even break");
proverbs.push("Never go to bed on an argument");
proverbs.push("Never judge a book by its cover");
proverbs.push("Never let the sun go down on your anger");
proverbs.push("Never look a gift horse in the mouth");
proverbs.push("Never put off until tomorrow what you can do today");
proverbs.push("Never speak ill of the dead");
proverbs.push("Never tell tales out of school");
proverbs.push("Nine tailors make a man");
proverbs.push("No man can serve two masters");
proverbs.push("No man is an island");
proverbs.push("No names, no pack-drill");
proverbs.push("No news is good news");
proverbs.push("No one can make you feel inferior without your consent");
proverbs.push("No pain, no gain");
proverbs.push("No rest for the wicked");
proverbs.push("Nothing is certain but death and taxes");
proverbs.push("Nothing succeeds like success");
proverbs.push("Nothing venture, nothing gain");
proverbs.push("Oil and water don't mix");
proverbs.push("Old soldiers never die, they just fade away");
proverbs.push("Once a thief, always a thief");
proverbs.push("Once bitten, twice shy");
proverbs.push("One good turn deserves another");
proverbs.push("One half of the world does not know how the other half lives");
proverbs.push("One hand washes the other");
proverbs.push("One man's meat is another man's poison");
proverbs.push("One might as well be hanged for a sheep as a lamb");
proverbs.push("One law for the rich and another for the poor");
proverbs.push("One swallow does not make a summer");
proverbs.push("One volunteer is worth ten pressed men");
proverbs.push("One year's seeding makes seven years weeding");
proverbs.push("Only fools and horses work");
proverbs.push("Opportunity never knocks twice at any man's door");
proverbs.push("Out of sight, out of mind");
proverbs.push("Parsley seed goes nine times to the Devil");
proverbs.push("Patience is a virtue");
proverbs.push("Pearls of wisdom");
proverbs.push("Penny wise and pound foolish");
proverbs.push("People who live in glass houses shouldn't throw stones");
proverbs.push("Physician, heal thyself");
proverbs.push("Possession is nine points of the law");
proverbs.push("Power corrupts; absolute power corrupts absolutely");
proverbs.push("Practice makes perfect");
proverbs.push("Practice what you preach");
proverbs.push("Prevention is better than cure");
proverbs.push("Pride goes before a fall");
proverbs.push("Procrastination is the thief of time");
proverbs.push("Put your best foot forward");
proverbs.push("Rain before seven, fine before eleven");
proverbs.push("Red sky at night shepherd's delight; red sky in the morning, shepherd's warning");
proverbs.push("Revenge is a dish best served cold");
proverbs.push("Revenge is sweet");
proverbs.push("Rob Peter to pay Paul");
proverbs.push("Rome wasn't built in a day");
proverbs.push("See a pin and pick it up, all the day you'll have good luck; see a pin and let it lie, bad luck you'll have all day");
proverbs.push("See no evil, hear no evil, speak no evil");
proverbs.push("Seeing is believing");
proverbs.push("Seek and ye shall find");
proverbs.push("Set a thief to catch a thief");
proverbs.push("Share and share alike");
proverbs.push("Shrouds have no pockets");
proverbs.push("Silence is golden");
proverbs.push("Slow but sure");
proverbs.push("Softly, softly, catchee monkey");
proverbs.push("Spare the rod and spoil the child");
proverbs.push("Speak as you find");
proverbs.push("Speak softly and carry a big stick");
proverbs.push("Sticks and stones may break my bones, but words will never hurt me");
proverbs.push("Still waters run deep");
proverbs.push("Strike while the iron is hot");
proverbs.push("Stupid is as stupid does");
proverbs.push("Success has many fathers, while failure is an orphan");
proverbs.push("Take care of the pence and the pounds will take care of themselves");
proverbs.push("Talk is cheap");
proverbs.push("Talk of the Devil, and he is bound to appear");
proverbs.push("Tell the truth and shame the Devil");
proverbs.push("That which does not kill us makes us stronger");
proverbs.push("The age of miracles is past");
proverbs.push("The apple never falls far from the tree");
proverbs.push("The best defence is a good offence");
proverbs.push("The best-laid schemes of mice and men gang aft agley");
proverbs.push("The best things in life are free");
proverbs.push("The bigger they are, the harder they fall");
proverbs.push("The bottom line is the bottom line");
proverbs.push("The boy is father to the man");
proverbs.push("The bread always falls buttered side down");
proverbs.push("The child is the father of the man");
proverbs.push("The cobbler always wears the worst shoes");
proverbs.push("The course of true love never did run smooth");
proverbs.push("The customer is always right");
proverbs.push("The darkest hour is just before the dawn");
proverbs.push("The devil finds work for idle hands to do");
proverbs.push("The devil looks after his own");
proverbs.push("The early bird catches the worm");
proverbs.push("The end justifies the means");
proverbs.push("The exception which proves the rule");
proverbs.push("The female of the species is more deadly than the male");
proverbs.push("The fruit does not fall far from the tree");
proverbs.push("The good die young");
proverbs.push("The grass is always greener on the other side of the fence");
proverbs.push("The hand that rocks the cradle rules the world");
proverbs.push("The husband is always the last to know");
proverbs.push("The labourer is worthy of his hire");
proverbs.push("The law is an ass");
proverbs.push("The leopard does not change his spots");
proverbs.push("The longest journey starts with a single step");
proverbs.push("The more the merrier");
proverbs.push("The more things change, the more they stay the same");
proverbs.push("The only good Indian is a dead Indian");
proverbs.push("The opera ain't over till the fat lady sings");
proverbs.push("The pen is mightier than sword");
proverbs.push("The price of liberty is eternal vigilance");
proverbs.push("The proof of the pudding is in the eating");
proverbs.push("The road to hell is paved with good intentions");
proverbs.push("The shoemaker's son always goes barefoot");
proverbs.push("The squeaking wheel gets the grease");
proverbs.push("The truth will out");
proverbs.push("The way to a man's heart is through his stomach");
proverbs.push("There are more ways of killing a cat than choking it with cream");
proverbs.push("There are none so blind as those, that will not see");
proverbs.push("There are two sides to every question");
proverbs.push("There but for the grace of God, go I");
proverbs.push("There's a time and a place for everything");
proverbs.push("There's an exception to every rule");
proverbs.push("There's always more fish in the sea");
proverbs.push("There's honour among thieves");
proverbs.push("There's many a good tune played on an old fiddle");
proverbs.push("There's many a slip 'twixt cup and lip");
proverbs.push("There's more than one way to skin a cat");
proverbs.push("There's no accounting for tastes");
proverbs.push("There's no fool like an old fool");
proverbs.push("There's no place like home");
proverbs.push("There's no smoke without fire");
proverbs.push("There's no such thing as a free lunch");
proverbs.push("There's no such thing as bad publicity");
proverbs.push("There's no time like the present");
proverbs.push("There's none so blind as those who will not see");
proverbs.push("There's none so deaf as those who will not hear");
proverbs.push("There's nowt so queer as folk");
proverbs.push("There's one born every minute");
proverbs.push("There's safety in numbers");
proverbs.push("They that sow the wind, shall reap the whirlwind");
proverbs.push("Third time lucky");
proverbs.push("Those who do not learn from history are doomed to repeat it");
proverbs.push("Those who live in glass houses shouldn't throw stones");
proverbs.push("Those who sleep with dogs will rise with fleas");
proverbs.push("Time and tide wait for no man");
proverbs.push("Time flies");
proverbs.push("Time is a great healer");
proverbs.push("Time is money");
proverbs.push("Time will tell");
proverbs.push("'tis better to have loved and lost, than never to have loved at all");
proverbs.push("To err is human; to forgive divine");
proverbs.push("To every thing there is a season");
proverbs.push("To the victor go the spoils");
proverbs.push("To travel hopefully is a better thing than to arrive");
proverbs.push("Tomorrow is another day");
proverbs.push("Tomorrow never comes");
proverbs.push("Too many cooks spoil the broth");
proverbs.push("Truth is stranger than fiction");
proverbs.push("Truth will out");
proverbs.push("Two blacks don't make a white");
proverbs.push("Two heads are better than one");
proverbs.push("Two is company, but three's a crowd");
proverbs.push("Two wrongs don't make a right");
proverbs.push("Variety is the spice of life");
proverbs.push("Virtue is its own reward");
proverbs.push("Walls have ears");
proverbs.push("Walnuts and pears you plant for your heirs");
proverbs.push("Waste not want not");
proverbs.push("What can't be cured must be endured");
proverbs.push("What goes up must come down");
proverbs.push("What you lose on the swings you gain on the roundabouts");
proverbs.push("What's sauce for the goose is sauce for the gander");
proverbs.push("When in Rome, do as the Romans do");
proverbs.push("When the cat's away the mice will play");
proverbs.push("When the going gets tough, the tough get going");
proverbs.push("When the oak is before the ash, then you will only get a splash; when the ash is before the oak, then you may expect a soak");
proverbs.push("What the eye doesn't see, the heart doesn't grieve over");
proverbs.push("Where there's a will there's a way");
proverbs.push("Where there's muck there's brass");
proverbs.push("While there's life there's hope");
proverbs.push("Whom the Gods love die young");
proverbs.push("Why keep a dog and bark yourself?");
proverbs.push("Women and children first");
proverbs.push("Wonders will never cease");
proverbs.push("Work expands so as to fill the time available");
proverbs.push("Worrying never did anyone any good");
proverbs.push("You are never too old to learn");
proverbs.push("You are what you eat");
proverbs.push("You can have too much of a good thing");
proverbs.push("You can lead a horse to water, but you can't make it drink");
proverbs.push("You can't have your cake and eat it");
proverbs.push("You can't get blood out of a stone");
proverbs.push("You can't make a silk purse from a sow's ear");
proverbs.push("You can't make an omelette without breaking eggs");
proverbs.push("You can't make bricks without straw");
proverbs.push("You can't run with the hare and hunt with the hounds");
proverbs.push("You can't teach an old dog new tricks");
proverbs.push("You can't judge a book by its cover");
proverbs.push("You can't win them all");
proverbs.push("You catch more flies with honey than with vinegar");
proverbs.push("You pays your money and you takes your choice");
proverbs.push("Youth is wasted on the young");
